apiVersion: v1
kind: Service
metadata:
  name: smart-meter-reader
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: smart-meter-reader
  selector:
    app: smart-reader-meter