apiVersion: v1
kind: Service
metadata:
  name: smart-meter-reader
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.59
  ports:
    - port: 8080
      protocol: TCP
      name: smart-meter-reader
  selector:
    app: smart-meter-reader