apiVersion: v1
kind: Secret
metadata:
  name: smart-meter-reader-secret
type: Opaque
data:
  METER_MPRN:  {{.Values.auth.meterMprn}}
  ESB_USER: {{.Values.auth.esbUser}}
  ESB_PASSWORD: {{.Values.auth.esbPass}}