apiVersion: v1
kind: Secret
metadata:
  name: smart-meter-reader-secret
type: Opaque
data:
  METER_MPRN:  {{.Values.auth.meterMprn}}
  ESB_USER: {{.Values.auth.esbUser}}
  ESB_PASSWORD: {{.Values.auth.esbPass}}
  MYSQL_ROOT_PASSWORD: {{.Values.auth.mysqlRootPass}}
  MYSQL_USER: {{.Values.auth.mysqlUser}}
  MYSQL_PASSWORD: {{.Values.auth.mysqlPass}}